### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by jmb** [jmb/NightLightPi#1]
The configuration of the script is a mess and could do with a clean up. It would probably be better in an external file.

**Comment by ghost** [comment]
Do you have any preferences on this? Here are some common approaches to external config

1. Create a config python module and declare all of your configuration as module level variables there
2. Use the standard library [ConfigParser](https://docs.python.org/3/library/configparser.html) that reads an external INI file
3. Use a YAML formatted external file, deserialized by [PyYAML](https://github.com/yaml/pyyaml)

I have some other questions too.

1. How do you want the user to interact with the configuration? Do you want them to SSH into the RPi and edit a file?
2. How do you want the program to find the config file? My personal favorite strategy is to use a fallback approach.
    1. Check for an environment variable NIGHTLIGHTPICONF which is a path to the file
    2. If that is missing or not set, then use XDG to check $HOME/.config/nightlightpi/nightlightpi.(conf/yaml/py).
    3. If there is no config file there, then use [pkg_resources](http://setuptools.readthedocs.io/en/latest/pkg_resources.html) to load a default config file that is shipped with the source code.
    4. Finally, if all else fails, the app Config object should have sane defaults where possible, and print helpful error messages for the user where sane defaults are not possible. 

Anyway, Let me know your thoughts. I'd like to make a contribution for Hacktoberfest.

**Comment by jmb** [comment]
Wow, thanks for the response!

I'm not sure on the best format for the external config - at the moment it's just a python data structure.

The config is non-user stuff and needs to be set when building the night light - number of LEDs, MQTT details etc. So I'm generally happy with the ssh approach.

Your suggestions sound good for finding the file - if it doesn't exist then I think the program shouldn't really load - there would be no way to determine GPIO pins or number of LEDs etc.

Happy to continue this discussion!

**Comment by ghost** [comment]
Let's give YAML a shot for the format of the file. It's easy to edit, well supported by the python community and allows for comments right in the config file which I think will be helpful considering the technical nature of the settings.

I have a few more questions before I can get started.

1. Do you ever expect to drive multiple devices from the same PI?
2. Which user on the pi will run nightlight.py? Does it require that the user be root?
3. If there are multiple users, should all users that run it share the same config? (basically, I'm trying to determine if the config should just go into /etc/nightlightpi/nightlightpi.yaml)

**Comment by jmb** [comment]
YAML sounds good to me!

At the moment I run on a dietpi setup as root (only user), but it could run as any user with access to the GPIO pins. I don't think it should be run by multiple users - it's essentially a service.

**Comment by ghost** [comment]
Understood. I will keep this simple and require that there be configuration stored in /etc/nightlightpi/nightlightpi.yaml. If that file doesn't exist then the program will log an error. I'll include a sample config with the repository that will be the reference for setting up a new system.

Go ahead and assign this one to me. I'll take a stab at it this evening when I get home from work.

**Comment by jmb** [comment]
Sounds brilliant!

**Comment by ghost** [comment]
I've been busy working on this. I've completed the implementation of locating and reading an external config. I now need to integrate this into the main module. Please have a look and let me know if you'd like me to change anything. I should be ready to submit a PR tonight.

https://github.com/wkmanire/NightLightPi/tree/feature/external-config

**Comment by ghost** [comment]
PR submitted.

**Comment by jmb** [comment]
Fantastic work by @wkmanire - thanks a lot!
